In [2]:
import numpy as np

In [6]:
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr)
print('________')

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
________


In [7]:
print(np.repeat(arr, repeats=2, axis=0))
print('________')
print(np.repeat(arr, repeats=2, axis=1))
print('________')
print(np.repeat(arr, repeats=2, axis=2))

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]
________
[[[1 2]
  [1 2]
  [3 4]
  [3 4]]

 [[5 6]
  [5 6]
  [7 8]
  [7 8]]]
________
[[[1 1 2 2]
  [3 3 4 4]]

 [[5 5 6 6]
  [7 7 8 8]]]


In [15]:
arr = np.array([1,2,3])
X = np.repeat(arr.reshape(1,-1,1), repeats=arr.shape[0], axis=0)
x = np.repeat(arr.reshape(-1,1,1), repeats=arr.shape[0], axis=1)

print(X)
print('________')
print(x)

[[[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]]
________
[[[1]
  [1]
  [1]]

 [[2]
  [2]
  [2]]

 [[3]
  [3]
  [3]]]


In [22]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print('________')
print(arr.reshape(-1,1,1))
print('________')


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
________
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]
________


In [23]:
print(arr.reshape(1,-1,1))
print('________')
print(arr.reshape(1,1,-1))
print('________')

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
________
[[[1 2 3 4 5 6 7 8]]]
________
