In [14]:
import numpy as np
import torch
import torch.nn as nn

import math

### np.repeat

In [6]:
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr)
print('________')

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
________


In [7]:
print(np.repeat(arr, repeats=2, axis=0))
print('________')
print(np.repeat(arr, repeats=2, axis=1))
print('________')
print(np.repeat(arr, repeats=2, axis=2))

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]
________
[[[1 2]
  [1 2]
  [3 4]
  [3 4]]

 [[5 6]
  [5 6]
  [7 8]
  [7 8]]]
________
[[[1 1 2 2]
  [3 3 4 4]]

 [[5 5 6 6]
  [7 7 8 8]]]


### np.array().rehsape

In [15]:
arr = np.array([1,2,3])
X = np.repeat(arr.reshape(1,-1,1), repeats=arr.shape[0], axis=0)
x = np.repeat(arr.reshape(-1,1,1), repeats=arr.shape[0], axis=1)

print(X)
print('________')
print(x)

[[[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]]
________
[[[1]
  [1]
  [1]]

 [[2]
  [2]
  [2]]

 [[3]
  [3]
  [3]]]


In [22]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print('________')
print(arr.reshape(-1,1,1))
print('________')


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
________
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]
________


In [23]:
print(arr.reshape(1,-1,1))
print('________')
print(arr.reshape(1,1,-1))
print('________')

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
________
[[[1 2 3 4 5 6 7 8]]]
________


# torch

### torch.inner

In [5]:
q = torch.Tensor([[[1, 1, 1], [0, -1, -1], [1, 2, 3], [-1, -2, -3]]
                  ,[[0, 1, 1], [0, -1, -1], [4, 5, 6], [-4, -5, -6]]]) # query
k = torch.Tensor([[[0, 1, 1], [0, -1, -1], [1, 2, 3], [-1, -2, -3]]
                  ,[[0, 1, 1], [0, -1, -1], [4, 5, 6], [-4, -5, -6]]]) # key

print("query size: ", q.size())
print("key size: ", k.size())

query size:  torch.Size([2, 4, 3])
key size:  torch.Size([2, 4, 3])


In [6]:
torch.inner(q,k).shape

torch.Size([2, 4, 2, 4])

In [7]:
print(torch.matmul(q, k.transpose(-2, -1)).shape)
print(torch.matmul(q, k.transpose(-2, -1)))

torch.Size([2, 4, 4])
tensor([[[  2.,  -2.,   6.,  -6.],
         [ -2.,   2.,  -5.,   5.],
         [  5.,  -5.,  14., -14.],
         [ -5.,   5., -14.,  14.]],

        [[  2.,  -2.,  11., -11.],
         [ -2.,   2., -11.,  11.],
         [ 11., -11.,  77., -77.],
         [-11.,  11., -77.,  77.]]])


In [8]:
print(torch.bmm(q, k.transpose(-2, -1)).shape)
torch.bmm(q, k.transpose(-2, -1))

torch.Size([2, 4, 4])


tensor([[[  2.,  -2.,   6.,  -6.],
         [ -2.,   2.,  -5.,   5.],
         [  5.,  -5.,  14., -14.],
         [ -5.,   5., -14.,  14.]],

        [[  2.,  -2.,  11., -11.],
         [ -2.,   2., -11.,  11.],
         [ 11., -11.,  77., -77.],
         [-11.,  11., -77.,  77.]]])

In [9]:
print(k.shape)
print(k)
print('________________________________')
print(k.transpose(-2, -1).shape)
print(k.transpose(-2, -1))

torch.Size([2, 4, 3])
tensor([[[ 0.,  1.,  1.],
         [ 0., -1., -1.],
         [ 1.,  2.,  3.],
         [-1., -2., -3.]],

        [[ 0.,  1.,  1.],
         [ 0., -1., -1.],
         [ 4.,  5.,  6.],
         [-4., -5., -6.]]])
________________________________
torch.Size([2, 3, 4])
tensor([[[ 0.,  0.,  1., -1.],
         [ 1., -1.,  2., -2.],
         [ 1., -1.,  3., -3.]],

        [[ 0.,  0.,  4., -4.],
         [ 1., -1.,  5., -5.],
         [ 1., -1.,  6., -6.]]])


In [13]:
torch.einsum('bij,bkj->bik', q, k)

tensor([[[  2.,  -2.,   6.,  -6.],
         [ -2.,   2.,  -5.,   5.],
         [  5.,  -5.,  14., -14.],
         [ -5.,   5., -14.,  14.]],

        [[  2.,  -2.,  11., -11.],
         [ -2.,   2., -11.,  11.],
         [ 11., -11.,  77., -77.],
         [-11.,  11., -77.,  77.]]])

In [11]:
print(torch.matmul(q, k.transpose(-2, -1)))

tensor([[[  2.,  -2.,   6.,  -6.],
         [ -2.,   2.,  -5.,   5.],
         [  5.,  -5.,  14., -14.],
         [ -5.,   5., -14.,  14.]],

        [[  2.,  -2.,  11., -11.],
         [ -2.,   2., -11.,  11.],
         [ 11., -11.,  77., -77.],
         [-11.,  11., -77.,  77.]]])


LazyLinear

In [18]:
tensor = torch.Tensor([[[1, 2, 3], [1, 2, 3]]])
Position_FFN_lazy = nn.LazyLinear(10)
out_l = Position_FFN_lazy(tensor)
print(tensor.shape) # [1, 2, 3]
print(out_l.shape) # [1, 2, 10]

torch.Size([1, 2, 3])
torch.Size([1, 2, 10])


In [19]:
print(out_l)

tensor([[[ 0.3929,  0.4674,  0.5755, -0.8578,  0.6716, -0.2799, -1.3265,
           2.0814,  0.9242,  1.8684],
         [ 0.3929,  0.4674,  0.5755, -0.8578,  0.6716, -0.2799, -1.3265,
           2.0814,  0.9242,  1.8684]]], grad_fn=<ViewBackward0>)
